version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=financedb
    depends_on:
      - db

  flyway:
    image: flyway/flyway:10.4
    container_name: flyway
    # yamllint disable rule:line-length
    command: |
      -url=jdbc:postgresql://db/financedb?allowPublicKeyRetrieval=true \
        -schemas=fam \
        -user=postgres -password=postgres -connectRetries=60 \
        -connectRetriesInterval=2 migrate
    # yamllint enable rule:line-length
    volumes:
      - ./data/db/schema:/flyway/sql
    depends_on:
      - db


  pgadmin:
    image: dpage/pgadmin4
    container_name: build-service-pgadmin4
    restart: always
    ports:
      - "8182:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fam.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financedb
    volumes:
      - db_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Optional for initialization

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - REACT_APP_BACKEND_URL=http://localhost:8080
  #   depends_on:
  #     - api

volumes:
  db_data: